COD-example update to work with HBase 2.4
cloudera/cod-examples pull request #11
Opened 2022-05-25 12:56 UTC by abhradeepkundu

2022-05-25 18:11 UTC, joshelser requested changes
Thanks for looking into this Abhradeep! A few suggestions for changes and one open-ended question about the hbase-shaded-client classpath (I haven't gone looking for any docs on HBase's upstream jira as to why otel jars aren't included, so there may be an obvious answer we just have to look for :))

2022-05-31 04:14 UTC, abhradeepkundu commented on phoenix-read-write/README.md
> +$ mvn clean package -P HBASE-2.4
I have made the change accordingly

2022-05-31 04:14 UTC, abhradeepkundu commented on phoenix-read-write/pom.xml
> +        <pch.artifactid.version>phoenix-client</pch.artifactid.version>
Done

2022-06-01 02:37 UTC, abhradeepkundu commented
> Thanks for looking into this Abhradeep! A few suggestions for changes and one open-ended question about the hbase-shaded-client classpath (I haven't gone looking for any docs on HBase's upstream jira as to why otel jars aren't included, so there may be an obvious answer we just have to look for :))

I have done the necessary changes. For Otel jar I still not found anything conclusive yet, still looking.

2022-06-01 02:39 UTC, abhradeepkundu commented
Sorry I have mistakenly closed the request earlier, opening it now

2022-06-01 12:24 UTC, petersomogyi commented
The `opentelemetry-api` and `opentelemetry-context` are transitive dependencies of hbase-shaded-client so there is no need to include them as dependencies. It needs to be added to `includeArtifactIds` only. Similarly, `htrace` is not needed anymore as `opentelemetry` replaced it. Cloudera Runtime versions before 7.2.14 still require htrace instead of opentelemetry.

```
[INFO] +- org.apache.hbase:hbase-shaded-client:jar:2.4.6.7.2.15.0-147:compile
[INFO] |  +- io.opentelemetry:opentelemetry-api:jar:0.12.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-context:jar:0.12.0:compile
[INFO] |  \- org.apache.yetus:audience-annotations:jar:0.5.0:compile
```

2022-08-05 09:01 UTC, petersomogyi approved these changes

2022-08-22 07:48 UTC, merged